# Generated by Django 4.1.7 on 2023-05-28 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_solicitante_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosBaneados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curp', models.CharField(max_length=18)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.solicitante')),
            ],
            options={
                'verbose_name': 'Usuario Baneado',
                'verbose_name_plural': 'Usuarios Baneados',
                'db_table': 'usuarios_baneados',
            },
        ),
    ]
