# Generated by Django 4.1.7 on 2023-06-09 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.solicitante'),
        ),
        migrations.AddField(
            model_name='modalidad',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.estatus'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.estatus'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='id_modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.modalidad'),
        ),
        migrations.AddField(
            model_name='documentosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convocatorias.solicitud'),
        ),
        migrations.AddField(
            model_name='atributosformulario',
            name='id_formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.formulario'),
        ),
    ]
