# Generated by Django 4.1.7 on 2023-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_alter_solicitud_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
