# Generated by Django 4.1.7 on 2023-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_alter_solicitud_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_solicitud', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10)),
                ('asunto', models.CharField(max_length=80)),
                ('comentarios', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
