# Generated by Django 4.1.7 on 2023-06-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='documentos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
