# Generated by Django 4.1.7 on 2023-06-09 03:19

import convocatorias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='documentos',
            field=models.CharField(blank=True, default=convocatorias.models.solicitud_directory_path, max_length=255, null=True),
        ),
    ]
