# Generated by Django 4.1.7 on 2023-04-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_modalidad_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributosformulario',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='atributosformulario',
            name='es_documento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=255),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
