# Generated by Django 4.1.7 on 2023-06-09 03:25

import convocatorias.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_alter_solicitud_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='documentos',
        ),
        migrations.CreateModel(
            name='DocumentoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=convocatorias.models.solicitud_directory_path)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convocatorias.solicitud')),
            ],
        ),
    ]
