# Generated by Django 4.1.7 on 2023-04-24 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_atributosformulario_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='estado',
        ),
        migrations.AddField(
            model_name='formulario',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.estatus'),
        ),
    ]
