# Generated by Django 4.1.7 on 2023-05-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_remove_formulario_estado_formulario_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributosformulario',
            name='archivo',
        ),
    ]
