# Generated by Django 4.1.7 on 2023-05-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_remove_atributosformulario_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributosformulario',
            name='nombre',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='atributosformulario',
            name='tipo_atributo',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Numero', 'Numero'), ('Fecha', 'Fecha'), ('Documento', 'Documento'), ('Telefono', 'Telefono')], max_length=15),
        ),
    ]
