# Generated by Django 4.1.7 on 2023-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_alter_atributosformulario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='requisitos',
            field=models.TextField(blank=True, default='sin requisitos', null=True),
        ),
    ]
