# Generated by Django 4.1.7 on 2023-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='curp',
            field=models.CharField(default='SIN CURP', max_length=18),
        ),
    ]
