# Generated by Django 4.1.7 on 2023-04-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_solicitante_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
