# Generated by Django 4.1.7 on 2023-06-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_solicitud', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10)),
                ('asunto', models.CharField(max_length=80)),
                ('comentarios', models.CharField(max_length=500)),
            ],
        ),
    ]
