# Generated by Django 4.1.7 on 2023-06-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitudApoyo',
            new_name='SolicitudSoporte',
        ),
    ]
