# Generated by Django 4.1.7 on 2023-07-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsoporte',
            name='estado_solicitud',
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='estado',
            field=models.CharField(choices=[('EN', 'En espera'), ('EA', 'En Atencion'), ('AT', 'Atendido')], default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='comentarios',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
